# version format
version: "{build}"
os: Windows Server 2012 R2
environment:
  GOPATH: c:\gopath
init:
- ps: >-
    $app = Get-WmiObject -Class Win32_Product -Filter "Vendor = 'http://golang.org'"

    if ($app) {
      $app.Uninstall()
    }
install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.5.windows-amd64.msi
  - msiexec /i go1.5.windows-amd64.msi /q
  - go version
  - go env
  - mkdir c:\gopath
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - go test ./...
test: off
deploy: off
