version: 2.1
jobs:
  build:
    branches:
      only:
        - master
        - hcl2
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
          GOPROXY: "https://proxy.golang.org"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mod-cache
      - run:
          name: "Tests"
          command: |
            go test ./...
      - save_cache:
          key: v1-mod-cache
          paths:
            - "/go/pkg/mod"
