version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "Prepare Artifact Store"
          command: |
            mkdir -p /tmp/artifacts
      - restore_cache:
          keys:
            - v1-mod-cache
      - run:
          name: "Tests"
          command: |
            .circleci/test.sh
      - save_cache:
          key: v1-mod-cache
          paths:
            - "/go/pkg/mod"
